Checkers 2.0/Pages/Game/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Checkers_2._0.Data;
using Checkers_2._0.Model;

namespace Checkers_2._0
{
    public class CreateModel : PageModel
    {
        private readonly Checkers_2._0.Data.ApplicationDbContext _db;

        public CreateModel(Checkers_2._0.Data.ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Game Game { get; set; }
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {

            //Game.Board = "1 0 1 0 1 0 1 0 0 1 0 1 0 1 0 1 1 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 2 0 2 0 2 0 2 2 0 2 0 2 0 2 0 0 2 0 2 0 2 0 2";
            Game.IsTurn = true;
            Game.gameState = 0;
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _db.Game.Add(Game);
            await _db.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Checkers 2.0/Pages/Game/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Checkers_2._0.Data;
using Checkers_2._0.Model;

namespace Checkers_2._0
{
    public class EditModel : PageModel
    {
        private readonly Checkers_2._0.Data.ApplicationDbContext _db;

        public EditModel(Checkers_2._0.Data.ApplicationDbContext db)
        {
            _db = db;
        }

        [BindProperty]
        public Game Game { get; set; }
        [TempData]
        public string buttonval { get; set; }
        public Board Board { get; set; }
        public string Data { get; set; }
        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Game = await _db.Game.FirstOrDefaultAsync(m => m.Id == id);
            Board = new Board(Game.Board);
            if (Game == null)
            {
                return NotFound();
            }
            return Page();
        }
        
        public async Task<IActionResult> OnPostCheck(string buttonval)
        {
            var xy = Array.ConvertAll(buttonval.Split(' '), int.Parse).ToList();
            int x = xy[0];
            int y = xy[1];
            Board = new Board(Game.Board);
            if (Board.PossibleMoves(x, y))
            {
                Game.IsTurn = !Game.IsTurn;
            }

            var GameFromDb = await _db.Game.FirstOrDefaultAsync(s => s.Id == Game.Id);
            GameFromDb.Board = Board.SaveBoard(Board.Storage);

            await _db.SaveChangesAsync();
            return Page();
        }
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var GameFromDb = await _db.Game.FirstOrDefaultAsync(g => g.Id == Game.Id );

            return RedirectToPage("./Index");
        }

        private bool GameExists(int id)
        {
            return _db.Game.Any(e => e.Id == id);
        }
    }
}

Checkers 2.0/Pages/Game/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Checkers_2._0.Data;
using Checkers_2._0.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace Checkers_2._0
{
    public class IndexModel : PageModel
    {
        private readonly ApplicationDbContext _db;
        public IndexModel(ApplicationDbContext db)
        {
            _db = db;
        }
        public IList<Game> Game { get; set; }
        public IList<Piece[,]> Board { get; set; }

        public async Task<IActionResult> OnGet()
        {
            Game = await _db.Game.ToListAsync();
            return Page();
        }
    }
}

Checkers 2.0/Pages/Game/Create.cshtml
@page

@model Checkers_2._0.CreateModel
@{
    ViewData["Title"] = "Create";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<br />
<h2 class="text-info">Create Service Type</h2>
<br />
<form method="post">
    <div class="border ">
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="Game.Player1"></label>
            </div>
            <div class="col-5">
                <input asp-for="Game.Player1" class="form-control" />
            </div>
            <span asp-validation-for="Game.Player1" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="Game.Player2"></label>
            </div>
            <div class="col-5">
                <input asp-for="Game.Player2" class="form-control" />
            </div>
            <span asp-validation-for="Game.Player2" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-2">
                <label asp-for="Game.Board"></label>
            </div>
            <div class="col-5">
                <input asp-for="Game.Board" class="form-control" />
            </div>
            <span asp-validation-for="Game.Board" class="text-danger"></span>
        </div>
        <div class="form-group row">
            <div class="col-5 offset-2">
                <partial name="_CreateAndBackToListButton" />
            </div>
        </div>
    </div>
</form>
@section Scripts{
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

Checkers 2.0/Pages/Game/Edit.cshtml
@page
@model Checkers_2._0.EditModel

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Edit</h1>
<form method="post">
    <input type="hidden" asp-for="Game.Board" />
    <input type="hidden" asp-for="Game.gameState" />
    <input type="hidden" asp-for="Game.IsTurn" />
    <input type="hidden" asp-for="Game.Player1" />
    <input type="hidden" asp-for="Game.Player2" />
    <div class="border">
        <input type="hidden" asp-for="Game.Id" />
        <table class="table border col-md-8">
            @for (int i = 0; i < 8; i++)
            {
                <tr>
                    @for (int j = 0; j < 8; j++)
                    {
                        if (Model.Board.Storage[i, j] != null)
                        {


                            if (Model.Board.Storage[i, j].Value == "red")
                            {

                                <td class="col-md-1" id="@(i.ToString() +" "+ j.ToString())">
                                    <button name="button" asp-route-id="" asp-route-buttonval="@(i.ToString() +" "+ j.ToString())" asp-page-handler="Check">Cervena</button>
                                </td>

                            }
                            if (Model.Board.Storage[i, j].Value == "black")
                            {
                                <td class="col-md-1" id="@(i.ToString() + j.ToString())">
                                    <button name="button" asp-route-id="" asp-route-buttonval="@(i.ToString() +" "+ j.ToString())" asp-page-handler="Check">Cerna</button>
                                </td>
                            }
                            if (Model.Board.Storage[i, j].Value == "redKing")
                            {
                                <td class="col-md-1" id="@(i.ToString() + j.ToString())">
                                    <button name="button" asp-route-id="" asp-route-buttonval="@(i.ToString() +" "+ j.ToString())" asp-page-handler="Check">Cervena Dáma</button>
                                </td>
                            }
                            if (Model.Board.Storage[i, j].Value == "blackKing")
                            {
                                <td class="col-md-1" id="@(i.ToString() + j.ToString())">
                                    <button name="button" asp-route-id="" asp-route-buttonval="@(i.ToString() +" "+ j.ToString())" asp-page-handler="Check">Cerna Dama</button>
                                </td>
                            }
                            if (Model.Board.Storage[i, j].Value == "green")
                            {
                                <td class="col-md-1" id="@(i.ToString() + j.ToString())">
                                    <button name="button" asp-route-id="" asp-route-buttonval="@(i.ToString() +" "+ j.ToString())" asp-page-handler="Check">Zelená</button>
                                </td>
                            }
                        }
                        else
                        {
                            <td class="col-md-1" id="@(i.ToString() + j.ToString())"></td>
                        }
                    }
                </tr>
            }
        </table>

    </div>
</form>
<div>

    @TempData["buttonval"]
</div>
<div>
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Checkers 2.0/Pages/Game/Index.cshtml
@page
@model Checkers_2._0.IndexModel
@{
    ViewData["Title"] = "Index";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h2 class="text-info">Game</h2>
<br />
<div class="border">
    <div class="row">
        <div class="col-6">
            <h2 class="text-info">Games</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-page="Create" class="btn btn-info">Create New</a>
        </div>
    </div>
</div>
<br />
<div>
    @if (Model.Game.Count() == 0)
    {
        <p>No Games exist plese add a game</p>
    }
    else
    {
        <table class="table table-striped border">
            <tr class="table-secondary">
                <th>
                    @Html.DisplayNameFor(m => m.Game[0].Id)
                </th>
                <th>
                    @Html.DisplayNameFor(m => m.Game[0].Player1)
                </th>
                <th>
                    @Html.DisplayNameFor(m => m.Game[0].Player2)
                </th>
                <th>
                    @Html.DisplayNameFor(m => m.Game[0].gameState)
                </th>
                <th>
                    @Html.DisplayNameFor(m => m.Game[0].Board)
                </th>
                <th></th>
            </tr>
            @foreach (var item in Model.Game)
            {
                if (User.Identity.Name == item.Player1 | User.Identity.Name == item.Player2)
                {
                <tr>
                    <td>
                        @Html.DisplayFor(m => item.Id)
                    </td>
                    <td>
                        @Html.DisplayFor(m => item.Player1)
                    </td>
                    <td>
                        @Html.DisplayFor(m => item.Player2)
                    </td>
                    <td>
                        @Html.DisplayFor(m => item.gameState)
                    </td>
                    <td>
                        @Html.DisplayFor(m => item.Board)
                    </td>
                    <td style="width:150px">
                        <div class=" btn-group" role="group">
                            <a class="btn btn-primary text-white" asp-page="Edit" asp-route-Id="@item.Id">Play</a>
                        </div>
                    </td>
                </tr>
                }
            }

        </table>
    }
</div>